temp_data_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: docker
      password: docker
      port: 5432
      dbname: postgres
      schema: temp_data
      threads: 1
      keepalives_idle: 0